cxf:
    path: /rest
deployment:
    kjars:
    -   alias: sboot2
        artifactId: business-application-kjar-2
        containerId: sboot2
        groupId: com.company
        version: 1.0-SNAPSHOT
jbpm:
  audit:
    auditEnabled: true
    enableProcessVariablesForTaskEvents: true
    executor:
        enabled: false
kieserver:
    casemgmt:
        enabled: true
    controllers: ws://localhost:8080/business-central/websocket/controller
    dmn:
        enabled: true
    drools:
        enabled: true
    jbpm:
        enabled: true
    jbpmui:
        enabled: true
    swagger:
        enabled: true    
    location: http://localhost:8095/rest/server
    serverId: sboot2
    serverName: sboot2
    logging:
    level:
        org:
            kie: INFO
server:
    address: 0.0.0.0
    port: 8095
spring:
    banner:
        location: classpath:banner.txt
    datasource:
        driver-class-name: org.h2.Driver
        password: sa
        url: jdbc:h2:mem:test
        username: sa
    h2:
      console:
        enabled: true    
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                hbm2ddl:
                    auto: update
                show_sql: false
    jta:
        narayana:
            transaction-manager-id: 1
            
            enabledEvents:
              - COMEPLETED_TASK
              - COMPLETED_PROCESS